CATEGORY_PROMPTS: dict[str, str] = {
    # Furniture / large appliances
    "refrigerator":        "modern kitchen interior, clean white walls, soft natural light, photorealistic",
    "dining table":        "bright Scandinavian dining room, wooden floor, natural window light, photorealistic",
    "fabric sofa":         "cosy living room interior, warm afternoon sunlight, neutral tones, photorealistic",
    "leather sofa":        "modern living room, light concrete walls, diffused daylight, photorealistic",
    "solid wood sofa":     "minimalist Japanese interior, tatami floor, soft ambient light, photorealistic",
    "leather bed":         "elegant bedroom, linen curtains, warm morning light, photorealistic",
    "fabric bed":          "bright bedroom interior, soft pastel tones, natural light, photorealistic",
    "sofa bed":            "contemporary living room, clean lines, warm neutral palette, photorealistic",
    "massage chair":       "modern wellness room, soft indirect lighting, neutral background, photorealistic",
    "computer chair":      "clean home office, light wooden desk, soft window light, photorealistic",
    "infant dining chair": "cheerful nursery room, pastel colours, soft diffused light, photorealistic",
    "bookshelf":           "minimalist study room, white walls, natural daylight, photorealistic",
    "computer desk":       "clean bright home office, soft window light, photorealistic",
    "latex mattress":      "bright bedroom, white bedding, airy natural light, photorealistic",

    # Kitchen / cooking appliances
    "electric pressure cooker": "modern kitchen counter, clean marble surface, bright kitchen light, photorealistic",
    "rice cooker":              "clean kitchen countertop, tile background, warm daylight, photorealistic",
    "wok":                      "bright professional kitchen counter, stainless steel surface, photorealistic",
    "electric baking pan":      "kitchen counter, bright overhead lighting, clean background, photorealistic",
    "induction cooker or electric ceramic cooker": "marble kitchen counter, modern kitchen, natural light, photorealistic",
    "coffee machine":           "cosy café counter, warm lighting, wood surface, photorealistic",
    "chef machine or dough mixer": "clean kitchen island, soft bright studio light, photorealistic",
    "wall breaking machine":    "modern kitchen counter, white tiles, bright natural light, photorealistic",
    "soup pot":                 "wooden kitchen table, rustic background, warm light, photorealistic",
    "multifunctional pot":      "clean kitchen surface, bright studio lighting, photorealistic",
    "health pot":               "wooden table, green plant nearby, warm natural light, photorealistic",
    "air fryer":                "bright kitchen counter, clean minimal background, photorealistic",
    "electric kettle":          "kitchen counter, morning light, clean bright setting, photorealistic",
    "hot pot":                  "restaurant setting, warm ambient lighting, dark wooden table, photorealistic",
    "meat grinder or vegetable cutting machine": "kitchen counter, clean bright background, photorealistic",
    "electric oven":            "bright modern kitchen, white tiles, soft light, photorealistic",

    # Watches
    "second hand watches":  "elegant dark display surface, jeweller's studio lighting, luxury feel, photorealistic",
    "national watch":       "polished marble surface, warm product photography lighting, photorealistic",
    "european and american watches": "premium dark velvet surface, dramatic side lighting, photorealistic",
    "japanese and korean watches":   "clean minimalist surface, soft diffused studio light, photorealistic",
    "swiss watch":          "luxury dark display background, jeweller's spotlight, photorealistic",
    "virtue watch":         "clean white display surface, soft studio lighting, photorealistic",
    "watch accessories":    "dark velvet display, warm accent lighting, photorealistic",

    # Small electronics
    "cell phone":           "clean white desk, minimal flat-lay, soft studio light, photorealistic",
    "laptop accessories":   "wooden desk, natural window light, clean background, photorealistic",
    "desktop":              "modern desk setup, clean white wall, bright office light, photorealistic",
    "monitor":              "clean office desk, soft ambient light, photorealistic",
    "tablet":               "white desk, flat-lay, bright minimalist studio, photorealistic",
    "keyboard":             "wooden desk, soft window light, clean setup, photorealistic",
    "mouse":                "clean desk surface, soft studio lighting, photorealistic",
    "mouse pad":            "wooden desk, soft diffused light, photorealistic",
    "graphics card":        "dark technical background, dramatic product lighting, photorealistic",
    "game notebook":        "dark gaming desk, RGB accent lighting, dramatic look, photorealistic",
    "notebook":             "wooden desk, natural light, clean background, photorealistic",
    "mobile power":         "clean white surface, soft product photography lighting, photorealistic",
    "printer":              "clean office setting, bright overhead light, photorealistic",
    "projector":            "dark home cinema setting, ambient warm glow, photorealistic",
    "speakers or audio":    "clean wooden shelf, soft warm light, photorealistic",
    "home theater":         "dark entertainment room, moody ambient lighting, photorealistic",
    "mp3 or mp4":           "clean white surface, bright product lighting, photorealistic",
    "bluetooth or wireless headphones": "dark premium surface, dramatic product lighting, photorealistic",
    "surveillance cameras": "clean neutral background, soft studio lighting, photorealistic",
    "sweeping robot":       "clean tile floor, bright home interior, photorealistic",
    "second-hand phone":    "clean white surface, bright product lighting, photorealistic",
    "mobile phone case or protective cover": "clean white desk, soft light, photorealistic",

    # Food & beverages
    "biscuits or puffed":   "rustic wooden table, natural daylight, food styling, photorealistic",
    "pastries or snacks":   "wooden serving board, bakery aesthetic, warm light, photorealistic",
    "pastry":               "marble table, elegant bakery setting, soft light, photorealistic",
    "chocolate":            "dark marble surface, dramatic side lighting, photorealistic",
    "candy":                "colourful flat-lay on bright pastel surface, photorealistic",
    "grains":               "rustic burlap surface, natural daylight, earthy tones, photorealistic",
    "beef":                 "butcher block wood, dramatic directional light, photorealistic",
    "chicken":              "clean white plate, bright food photography light, photorealistic",
    "fish":                 "crushed ice display, seafood market aesthetic, cool light, photorealistic",
    "mutton":               "wooden cutting board, warm rustic kitchen light, photorealistic",
    "hot pot":              "restaurant wooden table, warm ambient light, photorealistic",
    "instant food":         "clean kitchen counter, bright natural light, photorealistic",
    "dumplings or wontons": "bamboo steamer, warm steam, natural light, photorealistic",
    "seafood snacks":       "coastal wooden surface, natural beach light, photorealistic",
    "seafood dishes":       "elegant restaurant plate, dark background, spotlight, photorealistic",
    "delicatessen cured meat": "rustic wooden board, warm overhead light, photorealistic",
    "meat and poultry dishes": "elegant dining plate, warm restaurant light, photorealistic",
    "ice cream":            "bright pastel background, summer light, flat-lay, photorealistic",
    "dried tofu or vegetarian snacks": "clean neutral surface, soft natural light, photorealistic",

    # Tea & health products
    "longjing":             "elegant tea table, bamboo mat, soft natural light, photorealistic",
    "pu'er":                "dark wood tea table, warm atmospheric light, photorealistic",
    "tieguanyin":           "Chinese tea ceremony setting, ceramic background, soft light, photorealistic",
    "green tea":            "zen garden setting, bamboo, soft natural light, photorealistic",
    "black tea":            "cosy British afternoon tea setting, warm light, photorealistic",
    "white tea":            "clean white background, minimal tea styling, diffused light, photorealistic",
    "jasmine tea":          "floral white surface, natural spring light, photorealistic",
    "herbal tea":           "wooden rustic table, dried herbs, warm natural light, photorealistic",
    "complete tea set":     "traditional Chinese tea ceremony table, soft ambient light, photorealistic",
    "tea bar machine":      "modern tea shop counter, warm lighting, photorealistic",

    # Beauty & personal care
    "lotion or cream":      "clean white marble surface, soft product photography light, photorealistic",
    "toner or lotion":      "minimalist white studio, soft overhead light, photorealistic",
    "facial mask":          "spa setting, white marble, soft diffused light, photorealistic",
    "facial essence":       "luxury marble surface, elegant product lighting, photorealistic",
    "cleansing":            "clean bathroom counter, soft natural light, photorealistic",
    "shampoo":              "clean white bathroom surface, soft bright light, photorealistic",
    "body wash":            "spa bathroom setting, soft warm light, photorealistic",
    "perfume":              "luxury black velvet surface, dramatic directional light, photorealistic",
    "beauty device":        "clean white studio, soft product lighting, photorealistic",
    "sun protection":       "outdoor beach setting, soft bright daylight, photorealistic",

    # Clothing & accessories
    "bag":                  "clean studio background, soft fashion photography light, photorealistic",
    "women shoulder or crossbody bag": "elegant studio, soft neutral background, fashion light, photorealistic",
    "men backpack":         "outdoor urban setting, natural light, photorealistic",
    "business briefcase":   "office desk, professional warm lighting, photorealistic",
    "men wallet":           "leather desk surface, warm product lighting, photorealistic",
    "laptop bag":           "clean office setting, soft natural light, photorealistic",
    "suitcase":             "airport terminal, bright clean background, photorealistic",
    "men t-shirt":          "clean white studio, soft fashion photography light, photorealistic",
    "men jackets":          "urban outdoor setting, cool natural daylight, photorealistic",
    "men casual shoes":     "clean studio floor, soft side light, photorealistic",
    "sports and casual shoes": "clean studio, bright product photography light, photorealistic",
    "running shoes":        "athletic track background, action-inspired lighting, photorealistic",
    "men slippers":         "cosy home interior, warm soft light, photorealistic",
    "sports slippers":      "gym floor, bright overhead light, photorealistic",
    "casual pants":         "clean studio background, soft diffused light, photorealistic",
    "casual socks":         "clean wooden floor, bright flat-lay light, photorealistic",
    "pajamas or lounge clothes": "cosy bedroom setting, warm soft light, photorealistic",
    "sun hat":              "beach background, bright natural sunlight, photorealistic",
    "men underwear":        "clean white studio, minimal fashion lighting, photorealistic",
    "plus size women clothing": "bright clean studio, soft fashion light, photorealistic",
    "vest or vest":         "clean light studio, soft natural light, photorealistic",
    "shirt":                "clean white hanger, soft neutral light, photorealistic",

    # Jewellery
    "necklace":             "dark velvet display, warm jewellery lighting, photorealistic",
    "bracelet or anklet":   "polished marble surface, elegant product lighting, photorealistic",
    "earring":              "dark display background, jewellery spotlight, photorealistic",
    "jade pendant":         "natural stone surface, warm side lighting, photorealistic",
    "silver bracelet":      "dark velvet background, dramatic jewellery lighting, photorealistic",

    # Health / supplements
    "coenzyme q10":         "clean white pharmaceutical surface, bright studio light, photorealistic",
    "dried bird nest":      "ceramic bowl, traditional Chinese setting, warm light, photorealistic",
    "ready to eat bird nest": "elegant white ceramic, soft warm light, photorealistic",
    "dried sea cucumber":   "natural dark stone surface, earthy warm light, photorealistic",
    "cordyceps sinensis":   "wooden tray, traditional setting, warm natural light, photorealistic",
    "wolfberry":            "wooden bowl, natural rustic background, warm light, photorealistic",
    "nourish the liver or clear the lungs": "herbal clean background, soft natural light, photorealistic",
    "food and medicine come from the same source": "natural wooden surface, warm light, photorealistic",

    # Home & furniture
    "decorative ornaments": "bright minimalist shelf, neutral wall, soft ambient light, photorealistic",
    "multifunctional storage rack": "bright clean home interior, natural light, photorealistic",
    "storage box":          "clean organised room, soft overhead light, photorealistic",
    "ceiling lamp":         "bright white ceiling installation, clean interior, photorealistic",
    "mood lighting":        "dark cosy room, warm atmospheric glow, photorealistic",
    "scented candle":       "dark atmospheric setting, warm candlelight glow, photorealistic",
    "everlasting flower":   "bright minimal background, soft natural light, photorealistic",
    "music box":            "wooden surface, warm vintage light, photorealistic",
    "safe or box":          "clean neutral background, professional product lighting, photorealistic",
    "dish rack":            "bright kitchen setting, clean natural light, photorealistic",
    "draw paper":           "clean white desk, flat-lay, soft light, photorealistic",
    "this booklet or notes": "wooden desk, natural light, stationery flat-lay, photorealistic",

    # Appliances / home
    "washing machine":      "clean laundry room, bright white tiles, overhead light, photorealistic",
    "dryer":                "clean laundry room, bright background, photorealistic",
    "clothes dryer":        "bright bathroom or laundry, clean background, photorealistic",
    "air conditioner":      "clean modern living room, white walls, natural light, photorealistic",
    "air purifier":         "clean bright living room, modern interior, photorealistic",
    "water purifier":       "clean kitchen counter, bright lighting, photorealistic",
    "smart toilet":         "modern bathroom, clean white tiles, bright light, photorealistic",
    "bathroom cabinet":     "modern bathroom, clean white background, photorealistic",
    "sink":                 "modern kitchen or bathroom, clean surfaces, bright light, photorealistic",
    "toilet":               "clean modern bathroom, white tiles, photorealistic",
    "gas water heater":     "clean bathroom wall, bright bathroom light, photorealistic",
    "electric heater":      "cosy living room corner, warm ambient light, photorealistic",
    "bath heater":          "clean bathroom, bright natural light, photorealistic",

    # Food storage & tableware
    "ceramic or mug":       "wooden café table, warm coffee shop light, photorealistic",
    "cup":                  "clean kitchen surface, bright natural light, photorealistic",
    "bowl":                 "wooden dining table, warm food styling light, photorealistic",
    "glass":                "clean bar or kitchen surface, bright light, photorealistic",
    "plate or dish":        "elegant restaurant setting, warm directional light, photorealistic",
    "cutlery set":          "elegant dark dining table, warm restaurant light, photorealistic",
    "tableware and water utensils": "dining table, warm ambient light, photorealistic",
    "thermos cup":          "outdoor adventure setting, natural light, photorealistic",
    "thermos kettle":       "kitchen counter, warm morning light, photorealistic",
    "sport bottle":         "outdoor mountain or gym, bright active light, photorealistic",
    "plastic cup":          "clean white studio, soft bright light, photorealistic",
    "wine":                 "wine cellar or dark elegant bar, warm mood lighting, photorealistic",
    "liquor":               "premium dark bar counter, dramatic spotlight, photorealistic",
    "wine cabinet":         "elegant dining room, warm ambient light, photorealistic",

    # Miscellaneous
    "building blocks":      "bright children's playroom, colourful natural light, photorealistic",
    "early childhood education": "bright nursery, natural daylight, cheerful tones, photorealistic",
    "baby bottle nipple":   "clean white soft nursery background, photorealistic",
    "infant milk powder":   "clean baby product background, soft light, photorealistic",
    "children milk powder": "bright cheerful nursery, soft pastel background, photorealistic",
    "basketball":           "sports court, dramatic overhead light, photorealistic",
    "motorcycle helmet":    "clean studio, dramatic product lighting, photorealistic",
    "car perfume":          "clean car interior, bright modern light, photorealistic",
    "lighter":              "dark moody background, warm flame light, photorealistic",
    "outdoor tools":        "outdoor wilderness setting, natural rugged light, photorealistic",
    "rolling paper":        "clean neutral background, soft studio light, photorealistic",
    "switch socket":        "clean white wall, bright interior light, photorealistic",
    "broken wall or refined pieces": "construction site, natural industrial light, photorealistic",
    "chassis":              "dark premium tech background, dramatic product lighting, photorealistic",
    "projector":            "dark cinema room, ambient glow, photorealistic",
    "fish tank or aquarium": "clean aquarium shop, subtle blue ambient light, photorealistic",
    "seat cushion":         "bright living room, natural diffused light, photorealistic",
    "pillow cushion":       "cosy bright bedroom, soft natural light, photorealistic",
    "trend blind box":      "playful colourful background, soft studio light, photorealistic",
    "candied dried fruits": "rustic wooden surface, warm natural light, photorealistic",
    "roasted nuts":         "rustic wooden bowl, warm food photography light, photorealistic",
    "dried mushrooms":      "wooden cutting board, natural earthy light, photorealistic",
    "dried meat dried meat": "rustic wooden surface, warm directional light, photorealistic",
    "investment funds":     "clean professional desk, bright business setting, photorealistic",
    "investment collection": "elegant dark display, warm accent lighting, photorealistic",
    "accessories":          "clean neutral surface, soft product lighting, photorealistic",
}

DEFAULT_PROMPT = "clean white studio background, soft diffused product photography light, photorealistic"


def get_prompt(category: str) -> str:
    return CATEGORY_PROMPTS.get(category.lower(), DEFAULT_PROMPT)
